/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShipRouteImport } from './routes/ship'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountBillingRouteImport } from './routes/account/billing'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountPreferencesRouteImport } from './routes/account/preferences'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountShipmentsRouteImport } from './routes/account/shipments'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminShipmentsRouteImport } from './routes/admin/shipments'
import { Route as TrackIndexRouteImport } from './routes/track/index'
import { Route as TrackTrackingNumberRouteImport } from './routes/track/$trackingNumber'
import { Route as AccountShipmentsIdRouteImport } from './routes/account/shipments.$id'
import { Route as AdminShipmentsIdRouteImport } from './routes/admin/shipments.$id'
import { Route as AdminCustomersUserIdRouteImport } from './routes/admin/customers.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRoute = FreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipRoute = ShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountShipmentsRoute = AccountShipmentsRouteImport.update({
  id: '/account/shipments',
  path: '/account/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/admin/create',
  path: '/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/admin/shipments',
  path: '/admin/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackingNumberRoute = TrackTrackingNumberRouteImport.update({
  id: '/track/$trackingNumber',
  path: '/track/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountShipmentsIdRoute = AccountShipmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountShipmentsRoute,
} as any)
const AdminShipmentsIdRoute = AdminShipmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminShipmentsRoute,
} as any)
const AdminCustomersUserIdRoute = AdminCustomersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/freight': typeof FreightRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/services': typeof ServicesRoute
  '/ship': typeof ShipRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/shipments': typeof AccountShipmentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/shipments': typeof AdminShipmentsRouteWithChildren
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/track/': typeof TrackIndexRoute
  '/account/shipments/$id': typeof AccountShipmentsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/freight': typeof FreightRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/services': typeof ServicesRoute
  '/ship': typeof ShipRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/shipments': typeof AccountShipmentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/shipments': typeof AdminShipmentsRouteWithChildren
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/track': typeof TrackIndexRoute
  '/account/shipments/$id': typeof AccountShipmentsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/freight': typeof FreightRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/services': typeof ServicesRoute
  '/ship': typeof ShipRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/shipments': typeof AccountShipmentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/shipments': typeof AdminShipmentsRouteWithChildren
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/track/': typeof TrackIndexRoute
  '/account/shipments/$id': typeof AccountShipmentsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/checkout'
    | '/contact'
    | '/freight'
    | '/help'
    | '/locations'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/register'
    | '/returns'
    | '/services'
    | '/ship'
    | '/account/addresses'
    | '/account/billing'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/settings'
    | '/account/shipments'
    | '/admin/activity'
    | '/admin/create'
    | '/admin/customers'
    | '/admin/inbox'
    | '/admin/locations'
    | '/admin/payments'
    | '/admin/shipments'
    | '/track/$trackingNumber'
    | '/account/'
    | '/admin/'
    | '/track/'
    | '/account/shipments/$id'
    | '/admin/shipments/$id'
    | '/admin/customers/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/checkout'
    | '/contact'
    | '/freight'
    | '/help'
    | '/locations'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/register'
    | '/returns'
    | '/services'
    | '/ship'
    | '/account/addresses'
    | '/account/billing'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/settings'
    | '/account/shipments'
    | '/admin/activity'
    | '/admin/create'
    | '/admin/customers'
    | '/admin/inbox'
    | '/admin/locations'
    | '/admin/payments'
    | '/admin/shipments'
    | '/track/$trackingNumber'
    | '/account'
    | '/admin'
    | '/track'
    | '/account/shipments/$id'
    | '/admin/shipments/$id'
    | '/admin/customers/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/checkout'
    | '/contact'
    | '/freight'
    | '/help'
    | '/locations'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/register'
    | '/returns'
    | '/services'
    | '/ship'
    | '/account/addresses'
    | '/account/billing'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/settings'
    | '/account/shipments'
    | '/admin/activity'
    | '/admin/create'
    | '/admin/customers'
    | '/admin/inbox'
    | '/admin/locations'
    | '/admin/payments'
    | '/admin/shipments'
    | '/track/$trackingNumber'
    | '/account/'
    | '/admin/'
    | '/track/'
    | '/account/shipments/$id'
    | '/admin/shipments/$id'
    | '/admin/customers/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FreightRoute: typeof FreightRoute
  HelpRoute: typeof HelpRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  QuoteRoute: typeof QuoteRoute
  RegisterRoute: typeof RegisterRoute
  ReturnsRoute: typeof ReturnsRoute
  ServicesRoute: typeof ServicesRoute
  ShipRoute: typeof ShipRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountShipmentsRoute: typeof AccountShipmentsRouteWithChildren
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRouteWithChildren
  TrackTrackingNumberRoute: typeof TrackTrackingNumberRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight': {
      id: '/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof FreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship': {
      id: '/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof ShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/shipments': {
      id: '/account/shipments'
      path: '/account/shipments'
      fullPath: '/account/shipments'
      preLoaderRoute: typeof AccountShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/admin/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackingNumber': {
      id: '/track/$trackingNumber'
      path: '/track/$trackingNumber'
      fullPath: '/track/$trackingNumber'
      preLoaderRoute: typeof TrackTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/shipments/$id': {
      id: '/account/shipments/$id'
      path: '/$id'
      fullPath: '/account/shipments/$id'
      preLoaderRoute: typeof AccountShipmentsIdRouteImport
      parentRoute: typeof AccountShipmentsRoute
    }
    '/admin/shipments/$id': {
      id: '/admin/shipments/$id'
      path: '/$id'
      fullPath: '/admin/shipments/$id'
      preLoaderRoute: typeof AdminShipmentsIdRouteImport
      parentRoute: typeof AdminShipmentsRoute
    }
    '/admin/customers/$userId': {
      id: '/admin/customers/$userId'
      path: '/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AdminCustomersUserIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountShipmentsRouteChildren {
  AccountShipmentsIdRoute: typeof AccountShipmentsIdRoute
}

const AccountShipmentsRouteChildren: AccountShipmentsRouteChildren = {
  AccountShipmentsIdRoute: AccountShipmentsIdRoute,
}

const AccountShipmentsRouteWithChildren =
  AccountShipmentsRoute._addFileChildren(AccountShipmentsRouteChildren)

interface AdminShipmentsRouteChildren {
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
}

const AdminShipmentsRouteChildren: AdminShipmentsRouteChildren = {
  AdminShipmentsIdRoute: AdminShipmentsIdRoute,
}

const AdminShipmentsRouteWithChildren = AdminShipmentsRoute._addFileChildren(
  AdminShipmentsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersUserIdRoute: typeof AdminCustomersUserIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersUserIdRoute: AdminCustomersUserIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FreightRoute: FreightRoute,
  HelpRoute: HelpRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  QuoteRoute: QuoteRoute,
  RegisterRoute: RegisterRoute,
  ReturnsRoute: ReturnsRoute,
  ServicesRoute: ServicesRoute,
  ShipRoute: ShipRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountShipmentsRoute: AccountShipmentsRouteWithChildren,
  AdminActivityRoute: AdminActivityRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminInboxRoute: AdminInboxRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminShipmentsRoute: AdminShipmentsRouteWithChildren,
  TrackTrackingNumberRoute: TrackTrackingNumberRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
